# Generated by Django 4.2.4 on 2023-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_portfolio_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.CharField(max_length=230),
        ),
    ]
